USE [master]
GO

/****** Object:  Database [GlassPipes]    Script Date: 1/31/2016 2:32:22 PM ******/
DROP DATABASE [GlassPipes]
GO

/****** Object:  Database [GlassPipes]    Script Date: 1/31/2016 2:32:22 PM ******/
CREATE DATABASE [GlassPipes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GlassPipes', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GlassPipes.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GlassPipes_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GlassPipes_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GlassPipes] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GlassPipes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GlassPipes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GlassPipes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GlassPipes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GlassPipes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GlassPipes] SET ARITHABORT OFF 
GO

ALTER DATABASE [GlassPipes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GlassPipes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GlassPipes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GlassPipes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GlassPipes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GlassPipes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GlassPipes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GlassPipes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GlassPipes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GlassPipes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GlassPipes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GlassPipes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GlassPipes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GlassPipes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GlassPipes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GlassPipes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GlassPipes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GlassPipes] SET RECOVERY FULL 
GO

ALTER DATABASE [GlassPipes] SET  MULTI_USER 
GO

ALTER DATABASE [GlassPipes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GlassPipes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GlassPipes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GlassPipes] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GlassPipes] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GlassPipes] SET  READ_WRITE 
GO


